name: workflow a

on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
      - dequeued

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1
        if: github.event_name == 'pull_request'
      - run: |
          MIN=3
          MAX=10
          RANDOM_NUM=$(( RANDOM % (MAX - MIN + 1) + MIN ))
          sleep $RANDOM_NUM
        if: github.event_name == 'merge_group'
        shell: bash -xeuo pipefail {0}

  status-checks:
    runs-on: ubuntu-latest
    needs: job1
    if: always()
    steps:
      - run: echo exit
