name: workflow a

on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
      - dequeued

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          MIN=5
          MAX=15
          RANDOM_NUM=$(( RANDOM % (MAX - MIN + 1) + MIN ))
          sleep $(( RANDOM_NUM * 10 ))
        shell: bash -xeuo pipefail {0}

  status-checks:
    runs-on: ubuntu-latest
    needs: job1
    if: always()
    steps:
      - run: echo exit
